# This file was generated by GoReleaser. DO NOT EDIT.
cask "graft" do
  version "1.40.1"

  on_macos do
    on_arm do
      sha256 "2da7ee135938d7aa4fdd96c765887ab1717b4d395e1c8daf9cf39fc93566021f"
      url "https://github.com/fivetwenty-io/graft/releases/download/v#{version}/graft_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7aa9c2bc461d34d331167edd30c48be3889ed71d685a4d99213693deb30b50f0"
      url "https://github.com/fivetwenty-io/graft/releases/download/v#{version}/graft_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e5a89f125e3015546d254687cd31e74c71da7bbd7976d4bba56da13e4b701c02"
      url "https://github.com/fivetwenty-io/graft/releases/download/v#{version}/graft_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a6f52af43a23c5c9f93c99d8a0745418dde155daf46ef96299a30d1e8c65c9d6"
      url "https://github.com/fivetwenty-io/graft/releases/download/v#{version}/graft_#{version}_linux_amd64.tar.gz"
    end
  end

  name "graft"
  desc "YAML/JSON merging and templating CLI, spruce-compatible"
  homepage "https://github.com/fivetwenty-io/graft"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "graft"
  bash_completion "share/bash-completion/completions/graft.bash"
  fish_completion "share/fish/vendor_completions.d/graft.fish"
  zsh_completion "share/zsh/site-functions/_graft"

  # No zap stanza required
end
