# This file was generated by GoReleaser. DO NOT EDIT.
cask "graft" do
  version "1.38.0"

  on_macos do
    on_intel do
      sha256 "b53febd9293cae739b478f8efe533ded2af87b7287b14108380d7879cbd6b8fa"
      url "https://github.com/fivetwenty-io/graft/releases/download/v#{version}/graft_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3b1d87a784785fdf97285fcd79f035f6a3db7f0ef77453000231425447d67ddb"
      url "https://github.com/fivetwenty-io/graft/releases/download/v#{version}/graft_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dd3bf5c85093c1a35ed616eec9740b171245fa48ae35dc895434fd5cd6e10225"
      url "https://github.com/fivetwenty-io/graft/releases/download/v#{version}/graft_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "334c0a75d1db1e42c7d665e3353da2133b8ad456053bd9b9e07de79808b6bfdc"
      url "https://github.com/fivetwenty-io/graft/releases/download/v#{version}/graft_#{version}_linux_arm64.tar.gz"
    end
  end

  name "graft"
  desc "YAML/JSON merging and templating CLI, spruce-compatible"
  homepage "https://github.com/fivetwenty-io/graft"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "graft"
  bash_completion "share/bash-completion/completions/graft.bash"
  fish_completion "share/fish/vendor_completions.d/graft.fish"
  zsh_completion "share/zsh/site-functions/_graft"

  # No zap stanza required

end
