# This file was generated by GoReleaser. DO NOT EDIT.
cask "graft" do
  version "1.32.0"

  on_macos do
    on_intel do
      sha256 "4e803fd4d967f3cad5d3b355d208c98908208ea00eeaa23ca7332a789a745b8f"
      url "https://github.com/fivetwenty-io/graft/releases/download/v#{version}/graft_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "45a402afcefa7a7e0139069358946f5d2e8e7076293e3b3b316d586dbe29af9d"
      url "https://github.com/fivetwenty-io/graft/releases/download/v#{version}/graft_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "92196729d313b2cc53d897ad30116b00cb0de5d309322055f06eabf66f5f3b56"
      url "https://github.com/fivetwenty-io/graft/releases/download/v#{version}/graft_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d8b3f914bb06c3202346e9711d439befcd2e5b1126413b6c1b0d283ff5d8b521"
      url "https://github.com/fivetwenty-io/graft/releases/download/v#{version}/graft_#{version}_linux_arm64.tar.gz"
    end
  end

  name "graft"
  desc "YAML/JSON merging and templating CLI, spruce-compatible"
  homepage "https://github.com/fivetwenty-io/graft"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "graft"
  bash_completion "share/bash-completion/completions/graft.bash"
  fish_completion "share/fish/vendor_completions.d/graft.fish"
  zsh_completion "share/zsh/site-functions/_graft"

  # No zap stanza required

end
