# This file was generated by GoReleaser. DO NOT EDIT.
cask "ocfp" do
  version "0.2.13"

  on_macos do
    on_arm do
      sha256 "9792b4e956bd543647818cffe5f3ffb62f2183fee50bec480dac37d730decdb4"
      url "https://github.com/fivetwenty-io/ocfp-cli/releases/download/v#{version}/ocfp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "68b89ba7a36ba11938e1997c52e85dfe24eb64dde63a9a1306c64132169a6e7b"
      url "https://github.com/fivetwenty-io/ocfp-cli/releases/download/v#{version}/ocfp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7344a78efe0b54b4989aca084415dab089d8f55f7e4e45f57bf206db1cf8106f"
      url "https://github.com/fivetwenty-io/ocfp-cli/releases/download/v#{version}/ocfp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ff2509f38a0fb70a2de85a09a5c6471d00e5553733026beeed59a76929565906"
      url "https://github.com/fivetwenty-io/ocfp-cli/releases/download/v#{version}/ocfp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ocfp"
  desc "Open Cloud Foundry Platform CLI"
  homepage "https://github.com/fivetwenty-io/ocfp-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ocfp"
  bash_completion "share/bash-completion/completions/ocfp.bash"
  fish_completion "share/fish/vendor_completions.d/ocfp.fish"
  zsh_completion "share/zsh/site-functions/_ocfp"

  # No zap stanza required
end
