# This file was generated by GoReleaser. DO NOT EDIT.
cask "ocfp" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "{{staged_path}}/ocfp"],
          must_succeed: false, print_stderr: false,
          writable_paths: ["ocfp"], writable_base: :staged_path
    end
  end

  version "0.3.14"

  on_macos do
    on_arm do
      sha256 "ca45c20f478f0cbfbe35df55f213362ba27aaf793526b6967fa63d03a8d904f3"
      url "https://github.com/fivetwenty-io/ocfp-cli/releases/download/v#{version}/ocfp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5a8e95d83c5a26943bba66aa0db09dbc0c7172becb11c4a6cb2f1c673e637095"
      url "https://github.com/fivetwenty-io/ocfp-cli/releases/download/v#{version}/ocfp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6d9f9818c846c10d152996b7113da00369b7b07ba58497c233af74ae13322b9f"
      url "https://github.com/fivetwenty-io/ocfp-cli/releases/download/v#{version}/ocfp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a1b6eaba5420d547a713e0ba2af012601a059ada37f2a9cabf72ecba82586ce3"
      url "https://github.com/fivetwenty-io/ocfp-cli/releases/download/v#{version}/ocfp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ocfp"
  desc "Open Cloud Foundry Platform CLI"
  homepage "https://github.com/fivetwenty-io/ocfp-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ocfp"
  bash_completion "share/bash-completion/completions/ocfp.bash"
  fish_completion "share/fish/vendor_completions.d/ocfp.fish"
  zsh_completion "share/zsh/site-functions/_ocfp"

  # No zap stanza required
end
