# This file was generated by GoReleaser. DO NOT EDIT.
cask "ocfp" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "1f4cd91b12c9e4c35bba491b4365a5206d9c15209bafab8e5d6f1761c1594413"
      url "https://github.com/fivetwenty-io/ocfp-cli/releases/download/v#{version}/ocfp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ad7b5fcb25874868c905e8ad6462ab0e2323007861f45b71722d6edabeca42ea"
      url "https://github.com/fivetwenty-io/ocfp-cli/releases/download/v#{version}/ocfp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "030f8547808fd7e5f61b8d01ffa40b271dd8224f6b4e4297cc25694a3326412a"
      url "https://github.com/fivetwenty-io/ocfp-cli/releases/download/v#{version}/ocfp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ae99fbf7e6f7fd8114e7e2f37a53f07ef9d8bb09d168412830d44d7a80ccf45e"
      url "https://github.com/fivetwenty-io/ocfp-cli/releases/download/v#{version}/ocfp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ocfp"
  desc "Open Cloud Foundry Platform CLI"
  homepage "https://github.com/fivetwenty-io/ocfp-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ocfp"
  bash_completion "share/bash-completion/completions/ocfp.bash"
  fish_completion "share/fish/vendor_completions.d/ocfp.fish"
  zsh_completion "share/zsh/site-functions/_ocfp"

  # No zap stanza required
end
