# This file was generated by GoReleaser. DO NOT EDIT.
cask "pmx" do
  version "0.3.6"

  on_macos do
    on_arm do
      sha256 "f851aed0b9c0d60737d1bc8bb043c8f28966092d0d18d50ec2687406040d6b0c"
      url "https://github.com/fivetwenty-io/proxmox-cli/releases/download/v#{version}/pmx_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "48aea1462aacbf56b57bbcc8619fe489e3a5b5b2e3dee835799b46ff6ad9e86c"
      url "https://github.com/fivetwenty-io/proxmox-cli/releases/download/v#{version}/pmx_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "325263f5b01bd2cd81698b214d2106a8014fe414ffe041cadf94f257fda9390d"
      url "https://github.com/fivetwenty-io/proxmox-cli/releases/download/v#{version}/pmx_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pmx"
  desc "Proxmox command-line interface (VE / PBS / PDM)"
  homepage "https://github.com/fivetwenty-io/proxmox-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pmx"
  bash_completion "share/bash-completion/completions/pmx.bash"
  fish_completion "share/fish/vendor_completions.d/pmx.fish"
  zsh_completion "share/zsh/site-functions/_pmx"

  postflight do
    %w[pve pbs pdm].each do |persona|
      link = HOMEBREW_PREFIX/"bin"/persona
      link.delete if link.symlink? || link.exist?
      link.make_symlink("pmx")
    end
    # Bulk-link man pages and persona completions from the staged
    # cask content. Everything links into HOMEBREW_PREFIX in one quiet
    # pass; the uninstall hook removes any symlink in these dirs that
    # points back into this cask's Caskroom.
    %w[
      share/man/man1
      share/man/man5
      share/bash-completion/completions
      share/zsh/site-functions
      share/fish/vendor_completions.d
    ].each do |reldir|
      src = staged_path/reldir
      next unless src.directory?

      dst = HOMEBREW_PREFIX/reldir
      dst.mkpath
      src.children.each do |file|
        # pmx completions are already linked by the `completions:`
        # artifact stanza; skip them so the two mechanisms don't fight.
        next if %w[pmx.bash _pmx pmx.fish].include?(file.basename.to_s)

        link = dst/file.basename
        link.delete if link.symlink? || link.exist?
        link.make_symlink(file)
      end
    end
  end

  uninstall_postflight do
    %w[pve pbs pdm].each do |persona|
      link = HOMEBREW_PREFIX/"bin"/persona
      link.delete if link.symlink?
    end
    %w[
      share/man/man1
      share/man/man5
      share/bash-completion/completions
      share/zsh/site-functions
      share/fish/vendor_completions.d
    ].each do |reldir|
      dir = HOMEBREW_PREFIX/reldir
      next unless dir.directory?

      dir.children.each do |link|
        next unless link.symlink?

        link.delete if link.readlink.to_s.include?("/Caskroom/pmx/")
      end
    end
  end

  # No zap stanza required

end
