# This file was generated by GoReleaser. DO NOT EDIT.
cask "pmx" do
  version "0.6.3"

  on_macos do
    on_arm do
      sha256 "076e1d506251de328b1404d8e8901d08f3f923bd909d01745d6c20787bf40fdd"
      url "https://github.com/fivetwenty-io/proxmox-cli/releases/download/v#{version}/pmx_#{version}_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b48a99542fd5fe00b2ad2c976bffb9d98853c671c44ce1fb0c0cfcbbd5ca263b"
      url "https://github.com/fivetwenty-io/proxmox-cli/releases/download/v#{version}/pmx_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "afefacff089f02fcd40f3ce4f98b4750723e43c0b88367f313e7567f7570e3fe"
      url "https://github.com/fivetwenty-io/proxmox-cli/releases/download/v#{version}/pmx_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pmx"
  desc "Proxmox command-line interface (VE / PBS / PDM)"
  homepage "https://github.com/fivetwenty-io/proxmox-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pmx"

  postflight_steps do
    # pve, pbs, and pdm are pmx under a different argv[0] — internal/cli.Persona
    # reads it to pick the command tree — so each one has to be a link to the
    # binary rather than a copy of it.
    symlink "pmx", "bin/pve", source_base: :relative, target_base: :homebrew_prefix,
            overwrite: true, remove_on_uninstall: true
    symlink "pmx", "bin/pbs", source_base: :relative, target_base: :homebrew_prefix,
            overwrite: true, remove_on_uninstall: true
    symlink "pmx", "bin/pdm", source_base: :relative, target_base: :homebrew_prefix,
            overwrite: true, remove_on_uninstall: true

    # Create every target directory first. A globbed `symlink` that matches a
    # single file links to the target path itself unless that path is already
    # a directory, and man5 holds exactly one page — without this, a prefix
    # with no share/man/man5 yet would get a *file* named man5.
    mkdir_p "share/man/man1", base: :homebrew_prefix
    mkdir_p "share/man/man5", base: :homebrew_prefix
    mkdir_p "etc/bash_completion.d", base: :homebrew_prefix
    mkdir_p "share/zsh/site-functions", base: :homebrew_prefix
    mkdir_p "share/fish/vendor_completions.d", base: :homebrew_prefix

    # Bulk-link the man pages and every persona's completions out of the staged
    # cask content. A `manpage` artifact per file would print an ohai line on
    # every link and unlink, roughly 3,000 of them per install for pmx, and a
    # globbed symlink does the same work in silence.
    symlink "share/man/man1/*", "share/man/man1", source_base: :staged_path,
            target_base: :homebrew_prefix, source_glob: true, overwrite: true
    symlink "share/man/man5/*", "share/man/man5", source_base: :staged_path,
            target_base: :homebrew_prefix, source_glob: true, overwrite: true
    # Bash completions go to the compat directory, which bash-completion reads
    # whole. Its other directory loads a file only when the file is named for
    # the command, and these keep their .bash suffix.
    symlink "share/bash-completion/completions/*", "etc/bash_completion.d", source_base: :staged_path,
            target_base: :homebrew_prefix, source_glob: true, overwrite: true
    symlink "share/zsh/site-functions/*", "share/zsh/site-functions", source_base: :staged_path,
            target_base: :homebrew_prefix, source_glob: true, overwrite: true
    symlink "share/fish/vendor_completions.d/*", "share/fish/vendor_completions.d", source_base: :staged_path,
            target_base: :homebrew_prefix, source_glob: true, overwrite: true
  end

  uninstall_postflight_steps do
    # A globbed `symlink` records nothing per link for the uninstall phase, so
    # the links it made are swept out by hand here. Matching on the link target
    # leaves every other formula's and cask's links in these shared directories
    # alone.
    remove ["share/man/man1/*", "share/man/man5/*", "etc/bash_completion.d/*",
            "share/zsh/site-functions/*", "share/fish/vendor_completions.d/*"],
           base: :homebrew_prefix, symlink_target_contains: "/Caskroom/pmx/"
  end

  # No zap stanza required
end
